USE ProductValidation
GO

DROP TABLE ConfigValidationRuleLOV
DROP TABLE ConfigValidationRule
DROP TABLE Operator
DROP TABLE ConfigValidationMessage
DROP TABLE ConfigValidation
DROP TABLE BaseValidation
DROP TABLE FieldsContract
DROP TABLE Contracts
DROP TABLE FieldsProduct
DROP TABLE Products
DROP TABLE FieldsOffer
DROP TABLE Offers
DROP TABLE Fields
GO

CREATE TABLE Fields
(
	Id INT IDENTITY(1,1) NOT NULL,
	[Type] SMALLINT NOT NULL,
	[Name] VARCHAR(100) NOT NULL,
	Code VARCHAR(100) NOT NULL,
	Active BIT NOT NULL DEFAULT 1,
	Created DATETIME NOT NULL DEFAULT GETDATE(),	
	CONSTRAINT [PK_Fields] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],	
)

INSERT INTO FIELDS VALUES (1, 'NAME', 'CLIENT_NAME', 1, GETDATE())
INSERT INTO FIELDS VALUES (1, 'LAST NAME', 'CLIENT_LASTNAME', 1, GETDATE())
INSERT INTO FIELDS VALUES (2, 'AGE', 'CLIENT_AGE', 1, GETDATE())
INSERT INTO FIELDS VALUES (3, 'BIRTHDAY', 'CLIENT_BIRTHDAY', 1, GETDATE())
INSERT INTO FIELDS VALUES (4, 'HEIGHT', 'CLIENT_HEIGHT', 1, GETDATE())
INSERT INTO FIELDS VALUES (4, 'WEIGHT', 'CLIENT_WEIGHT', 1, GETDATE())

CREATE TABLE Offers
(
	Id INT IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(100) NOT NULL,
	Active BIT NOT NULL DEFAULT 1,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT [PK_Offers] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],	
)

INSERT INTO OFFERS VALUES ('TEST OFFER', 1, GETDATE()) 

CREATE TABLE FieldsOffer
(
	Id INT IDENTITY(1,1) NOT NULL,
	FieldId INT NOT NULL,
	OfferId INT NOT NULL,	
	Active BIT NOT NULL DEFAULT 1,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT [PK_FieldsOffer] PRIMARY KEY CLUSTERED 
		(FieldId, OfferId ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],	
	CONSTRAINT [FK_FieldsOffer_Fields] FOREIGN KEY ([FieldId]) REFERENCES [Fields] ([Id]),
	CONSTRAINT [FK_FieldsOffer_Offers] FOREIGN KEY ([OfferId]) REFERENCES [Offers] ([Id])
)

INSERT INTO FIELDSOFFER VALUES(1, 1, 1, GETDATE())
INSERT INTO FIELDSOFFER VALUES(2, 1, 1, GETDATE())
INSERT INTO FIELDSOFFER VALUES(3, 1, 1, GETDATE())
INSERT INTO FIELDSOFFER VALUES(4, 1, 1, GETDATE())
INSERT INTO FIELDSOFFER VALUES(5, 1, 1, GETDATE())
INSERT INTO FIELDSOFFER VALUES(6, 1, 1, GETDATE())

CREATE TABLE Products
(
	Id INT IDENTITY(1,1) NOT NULL,
	OfferId INT NOT NULL,
	[Name] VARCHAR(100) NOT NULL,
	Active BIT NOT NULL DEFAULT 1,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],	
	CONSTRAINT [FK_Products_Offers] FOREIGN KEY ([OfferId]) REFERENCES [Offers] ([Id])
)

INSERT INTO PRODUCTS VALUES (1,'PRODUCT CLIENT', 1, GETDATE())

CREATE TABLE FieldsProduct
(
	Id INT IDENTITY(1,1) NOT NULL,
	FieldId INT NOT NULL,
	ProductId INT NOT NULL,
	IsEditable BIT NOT NULL,
	IsVisible BIT NOT NULL,
	DefaultValue VARCHAR(200) NULL,
	Active BIT NOT NULL DEFAULT 1,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT [PK_FieldsProduct] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],	
	CONSTRAINT [FK_FieldsProduct_Fields] FOREIGN KEY ([FieldId]) REFERENCES [Fields] ([Id]),
	CONSTRAINT [FK_FieldsProduct_Products] FOREIGN KEY ([ProductId]) REFERENCES [Products] ([Id])
)

INSERT INTO FIELDSPRODUCT VALUES (1, 1, 1, 1, NULL, 1, GETDATE())
INSERT INTO FIELDSPRODUCT VALUES (2, 1, 1, 1, NULL, 1, GETDATE())
INSERT INTO FIELDSPRODUCT VALUES (3, 1, 1, 1, NULL, 1, GETDATE())
INSERT INTO FIELDSPRODUCT VALUES (4, 1, 1, 1, NULL, 1, GETDATE())
INSERT INTO FIELDSPRODUCT VALUES (5, 1, 1, 1, NULL, 1, GETDATE())
INSERT INTO FIELDSPRODUCT VALUES (6, 1, 1, 1, NULL, 1, GETDATE())

CREATE TABLE Contracts
(
	Id INT IDENTITY(1,1) NOT NULL,
	ProductId INT NOT NULL,
	Aproved BIT NOT NULL DEFAULT 0,
	ErrorValidation NVARCHAR(MAX) NULL,
	Active BIT NOT NULL DEFAULT 1,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT [PK_Contracts] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_Contracts_Product] FOREIGN KEY ([ProductId]) REFERENCES [Products] ([Id])
)

INSERT INTO CONTRACTS VALUES (1, 0, NULL, 1, GETDATE())

CREATE TABLE FieldsContract
(
	Id INT IDENTITY(1,1) NOT NULL,
	FieldProductId INT NOT NULL,
	ContractId INT NOT NULL,
	[Value] NVARCHAR(MAX) NULL,
	Active BIT NOT NULL DEFAULT 1,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT [PK_FieldsContract] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_FieldsContract_FieldsProduct] FOREIGN KEY ([FieldProductId]) REFERENCES [FieldsProduct] ([Id]),
	CONSTRAINT [FK_FieldsContract_Contract] FOREIGN KEY ([ContractId]) REFERENCES [Contracts] ([Id])
)

INSERT INTO FIELDSCONTRACT VALUES (1, 1, 'BRUNO', 1, GETDATE())
INSERT INTO FIELDSCONTRACT VALUES (2, 1, 'PAPA', 1, GETDATE())
INSERT INTO FIELDSCONTRACT VALUES (3, 1, '38', 1, GETDATE())
INSERT INTO FIELDSCONTRACT VALUES (4, 1, '10/11/1984', 1, GETDATE())
INSERT INTO FIELDSCONTRACT VALUES (5, 1, '1,80', 1, GETDATE())
INSERT INTO FIELDSCONTRACT VALUES (6, 1, '98,8', 1, GETDATE())


CREATE TABLE BaseValidation
(
	Id INT IDENTITY(1,1) NOT NULL,
	BaseProductId INT NOT NULL,
	IsExternal BIT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_BaseValidation] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_BaseValidation_Products] FOREIGN KEY ([BaseProductId]) REFERENCES [Products] ([Id])
)

INSERT INTO BASEVALIDATION VALUES (1, 0)

CREATE TABLE ConfigValidation
(
	Id INT IDENTITY(1,1) NOT NULL,
	ConfigVersionId INT NOT NULL,
	IsExternal BIT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_ConfigValidation] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
)

INSERT INTO ConfigValidation VALUES (1, 0)

CREATE TABLE ConfigValidationMessage
(
	Id INT IDENTITY(1,1) NOT NULL,
	ConfigValidationId INT NOT NULL,
	BaseValidationId INT NOT NULL,
	LanguageId INT NOT NULL,
	Message varchar(max) NOT NULL,
	IsExternal BIT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_ConfigValidationMessage] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_ConfigValidationMessage_BaseValidation] FOREIGN KEY ([BaseValidationId]) REFERENCES [BaseValidation] ([Id]),
	CONSTRAINT [FK_ConfigValidationMessage_ConfigValidation] FOREIGN KEY ([ConfigValidationId]) REFERENCES [ConfigValidation] ([Id])
)

INSERT INTO ConfigValidationMessage VALUES (1, 1, 1, 'Validação do cliente com erro', 0)
INSERT INTO ConfigValidationMessage VALUES (1, 1, 2, 'Error client validation', 0)

CREATE TABLE Operator
(
	Id INT IDENTITY(1,1) NOT NULL,
	Code VARCHAR(100) NOT NULL,
	[Label] varchar(100) NOT NULL,
	Is_Active BIT NOT NULL DEFAULT 0,
	IsFieldLOV BIT NOT NULL DEFAULT 0,
	IsField_Integer BIT NOT NULL DEFAULT 0,
	IsField_Decimal BIT NOT NULL DEFAULT 0,
	IsField_Text BIT NOT NULL DEFAULT 0,
	IsField_Date BIT NOT NULL DEFAULT 0,
	IsRisk BIT NOT NULL DEFAULT 0,
	IsFieldRiskLOV BIT NOT NULL DEFAULT 0,
	IsFieldRisk BIT NOT NULL DEFAULT 0,
	[Message] VARCHAR(max) NOT NULL,
	IsExternal BIT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_Operator] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
)

INSERT INTO Operator VALUES ('CLIENT_NAME', 'NAME', 1, 0, 0, 0, 1, 0, 0, 0, 0, 'Nome inválido', 0)
INSERT INTO Operator VALUES ('CLIENT_LASTNAME', 'LAST NAME', 1, 0, 0, 0, 1, 0, 0, 0, 0, 'Último nome inválido', 0)
INSERT INTO Operator VALUES ('CLIENT_AGE', 'AGE', 1, 0, 1, 0, 0, 0, 0, 0, 0, 'Idade inválida', 0)
INSERT INTO Operator VALUES ('CLIENT_BIRTHDAY', 'BIRTHDAY', 1, 0, 0, 0, 0, 1, 0, 0, 0, 'Data de aniversário inválida', 0)
INSERT INTO Operator VALUES ('CLIENT_HEIGHT', 'HEIGHT', 1, 0, 0, 1, 0, 0, 0, 0, 0, 'Altura inválida', 0)
INSERT INTO Operator VALUES ('CLIENT_WEIGHT', 'WEIGHT', 1, 0, 0, 1, 0, 0, 0, 0, 0, 'Peso inválido', 0)

CREATE TABLE ConfigValidationRule
(
	Id INT IDENTITY(1,1) NOT NULL,
	ConfigValidationId INT NOT NULL,
	BaseValidationId INT NOT NULL,
	RuleDescription varchar(100) NOT NULL,
	IsFieldChoice BIT NOT NULL DEFAULT 0,
	RuleTypeId INT NOT NULL,
	LeftFieldId INT NOT NULL,
	LeftRiskFieldId INT NOT NULL,
	OperatorId INT NOT NULL,
	ValueText VARCHAR(100) NULL,
	ValueDate DATETIME NULL,
	ValueMin BIGINT NULL,
	ValueMax BIGINT NULL,
	ValueSelect VARCHAR(100) NULL,
	ValueNull BIT NOT NULL DEFAULT 0,
	BaseLoveEntryId INT NULL,
	Severity INT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_ConfigValidationRule] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_ConfigValidationRule_BaseValidation] FOREIGN KEY ([BaseValidationId]) REFERENCES [BaseValidation] ([Id]),
	CONSTRAINT [FK_ConfigValidationRule_ConfigValidation] FOREIGN KEY ([ConfigValidationId]) REFERENCES [ConfigValidation] ([Id]),
	CONSTRAINT [FK_ConfigValidationRule_Operator] FOREIGN KEY ([OperatorId]) REFERENCES [Operator] ([Id])
)

INSERT INTO ConfigValidationRule VALUES (1,1,'RULE NAME EMPTY',0,1,0,0,1,NULL,NULL,NULL,NULL,NULL,0,NULL,1)
INSERT INTO ConfigValidationRule VALUES (1,1,'RULE LAST NAME EMPTY',0,1,0,0,2,NULL,NULL,NULL,NULL,NULL,0,NULL,1)
INSERT INTO ConfigValidationRule VALUES (1,1,'RULE AGE EMPTY',0,1,0,0,3,NULL,NULL,NULL,NULL,NULL,0,NULL,1)
INSERT INTO ConfigValidationRule VALUES (1,1,'RULE BIRTHDAY EMPTY',0,1,0,0,4,NULL,NULL,NULL,NULL,NULL,0,NULL,1)
INSERT INTO ConfigValidationRule VALUES (1,1,'RULE AGE >= 18',0,14,0,0,3,NULL,NULL,18,NULL,NULL,0,NULL,1)

CREATE TABLE ConfigValidationRuleLOV
(
	Id INT IDENTITY(1,1) NOT NULL,
	ConfigValidationRuleId INT NOT NULL,
	BaseLOVEntryId INT NOT NULL,
	CONSTRAINT [PK_ConfigValidationRuleLOV] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_ConfigValidationRuleLOV_ConfigValidationRule] FOREIGN KEY ([ConfigValidationRuleId]) REFERENCES [ConfigValidationRule] ([Id])
)


