USE ProductValidation
GO

DROP TABLE ConfigValidationRuleLOV
DROP TABLE ConfigValidationRule
DROP TABLE Operator
DROP TABLE ConfigValidationMessage
DROP TABLE ConfigValidation
DROP TABLE BaseValidation

CREATE TABLE BaseValidation
(
	Id INT IDENTITY(1,1) NOT NULL,
	BaseProductId INT NOT NULL,
	IsExternal BIT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_BaseValidation] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
)

INSERT INTO BASEVALIDATION VALUES (1, 0)

CREATE TABLE ConfigValidation
(
	Id INT IDENTITY(1,1) NOT NULL,
	ConfigVersionId INT NOT NULL,
	IsExternal BIT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_ConfigValidation] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
)

INSERT INTO ConfigValidation VALUES (1, 0)

CREATE TABLE ConfigValidationMessage
(
	Id INT IDENTITY(1,1) NOT NULL,
	ConfigValidationId INT NOT NULL,
	BaseValidationId INT NOT NULL,
	LanguageId INT NOT NULL,
	Message varchar(max) NOT NULL,
	IsExternal BIT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_ConfigValidationMessage] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_ConfigValidationMessage_BaseValidation] FOREIGN KEY ([BaseValidationId]) REFERENCES [BaseValidation] ([Id]),
	CONSTRAINT [FK_ConfigValidationMessage_ConfigValidation] FOREIGN KEY ([ConfigValidationId]) REFERENCES [ConfigValidation] ([Id])
)

INSERT INTO ConfigValidationMessage VALUES (1, 1, 1, 'Validação do cliente com erro', 0)
INSERT INTO ConfigValidationMessage VALUES (1, 1, 2, 'Error client validation', 0)

CREATE TABLE Operator
(
	Id INT IDENTITY(1,1) NOT NULL,
	Code VARCHAR(100) NOT NULL,
	[Label] varchar(100) NOT NULL,
	Is_Active BIT NOT NULL DEFAULT 0,
	IsFieldLOV BIT NOT NULL DEFAULT 0,
	IsField_Integer BIT NOT NULL DEFAULT 0,
	IsField_Decimal BIT NOT NULL DEFAULT 0,
	IsField_Text BIT NOT NULL DEFAULT 0,
	IsField_Date BIT NOT NULL DEFAULT 0,
	IsRisk BIT NOT NULL DEFAULT 0,
	IsFieldRiskLOV BIT NOT NULL DEFAULT 0,
	IsFieldRisk BIT NOT NULL DEFAULT 0,
	[Message] VARCHAR(max) NOT NULL,
	IsExternal BIT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_Operator] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]	
)

INSERT INTO Operator VALUES ('CLIENT_NAME', 'NAME', 1, 0, 0, 0, 1, 0, 0, 0, 0, 'Nome inválido', 0)
INSERT INTO Operator VALUES ('CLIENT_LASTNAME', 'LAST NAME', 1, 0, 0, 0, 1, 0, 0, 0, 0, 'Último nome inválido', 0)
INSERT INTO Operator VALUES ('CLIENT_AGE', 'AGE', 1, 0, 1, 0, 0, 0, 0, 0, 0, 'Idade inválida', 0)
INSERT INTO Operator VALUES ('CLIENT_BIRTHDAY', 'BIRTHDAY', 1, 0, 0, 0, 0, 1, 0, 0, 0, 'Data de aniversário inválida', 0)
INSERT INTO Operator VALUES ('CLIENT_HEIGHT', 'HEIGHT', 1, 0, 0, 1, 0, 0, 0, 0, 0, 'Altura inválida', 0)
INSERT INTO Operator VALUES ('CLIENT_WEIGHT', 'WEIGHT', 1, 0, 0, 1, 0, 0, 0, 0, 0, 'Peso inválido', 0)

CREATE TABLE ConfigValidationRule
(
	Id INT IDENTITY(1,1) NOT NULL,
	ConfigValidationId INT NOT NULL,
	BaseValidationId INT NOT NULL,
	RuleDescription varchar(100) NOT NULL,
	IsFieldChoice BIT NOT NULL DEFAULT 0,
	RuleTypeId INT NOT NULL,
	LeftFieldId INT NOT NULL,
	LeftRiskFieldId INT NOT NULL,
	OperatorId INT NOT NULL,
	ValueText VARCHAR(100) NULL,
	ValueDate DATETIME NULL,
	ValueMin BIGINT NULL,
	ValueMax BIGINT NULL,
	ValueSelect VARCHAR(100) NULL,
	ValueNull BIT NOT NULL DEFAULT 0,
	BaseLoveEntryId INT NULL,
	Severity INT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_ConfigValidationRule] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_ConfigValidationRule_BaseValidation] FOREIGN KEY ([BaseValidationId]) REFERENCES [BaseValidation] ([Id]),
	CONSTRAINT [FK_ConfigValidationRule_ConfigValidation] FOREIGN KEY ([ConfigValidationId]) REFERENCES [ConfigValidation] ([Id]),
	CONSTRAINT [FK_ConfigValidationRule_Operator] FOREIGN KEY ([OperatorId]) REFERENCES [Operator] ([Id])
)

INSERT INTO ConfigValidationRule VALUES (1,1,'RULE NAME NOT EMPTY',0,2,0,0,1,NULL,NULL,NULL,NULL,NULL,0,NULL,1)
INSERT INTO ConfigValidationRule VALUES (1,1,'RULE LAST NAME NOT EMPTY',0,2,0,0,2,NULL,NULL,NULL,NULL,NULL,0,NULL,1)
INSERT INTO ConfigValidationRule VALUES (1,1,'RULE AGE NOT EMPTY',0,2,0,0,3,NULL,NULL,NULL,NULL,NULL,0,NULL,1)
INSERT INTO ConfigValidationRule VALUES (1,1,'RULE BIRTHDAY NOT EMPTY',0,2,0,0,4,NULL,NULL,NULL,NULL,NULL,0,NULL,1)
INSERT INTO ConfigValidationRule VALUES (1,1,'RULE AGE >= 18',0,14,0,0,3,NULL,NULL,18,NULL,NULL,0,NULL,1)

CREATE TABLE ConfigValidationRuleLOV
(
	Id INT IDENTITY(1,1) NOT NULL,
	ConfigValidationRuleId INT NOT NULL,
	BaseLOVEntryId INT NOT NULL,
	CONSTRAINT [PK_ConfigValidationRuleLOV] PRIMARY KEY CLUSTERED 
		([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	CONSTRAINT [FK_ConfigValidationRuleLOV_ConfigValidationRule] FOREIGN KEY ([ConfigValidationRuleId]) REFERENCES [ConfigValidationRule] ([Id])
)


